name: Check Pull Request

on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm run test
      - name: Lint
        run: pnpm run lint:check
      - name: Format Check
        run: pnpm run format:check
      - name: Build
        run: pnpm run build
  auto-approve:
    runs-on: ubuntu-latest
    needs: check
    if: |
      github.event.pull_request.user.login == github.repository_owner && ! github.event.pull_request.draft
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
