name: Publish Github Packages

on:
  push:
    tags:
      - v*.*.*

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm publish
        env:
          GITHUB_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
