name: Create Relase

on:
  push:
    tags:
      - v*.*.*

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install
        run: pnpm install
      - name: Test
        run: pnpm run test
      - name: Lint
        run: pnpm run lint:check
      - name: Format Check
        run: pnpm run format:check
      - name: Build
        run: pnpm run build
  publish:
    runs-on: ubuntu-22.04
    needs: check
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
      - name: Install
        run: pnpm install
      - name: Build
        run: pnpm run build
      - name: Publish
        run: pnpm publish
        env:
          GITHUB_PKG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    runs-on: ubuntu-latest
    needs: check
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get Tag Name
        run: echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Create Relase
        run: gh release create "${{env.TAG_NAME}}" --generate-notes
